### PR TITLE
Updates the django version and remove dependences

### PR DESCRIPTION
**Pull request by jroquejr**
Updates the Django version and remove dependencies: mysql and "South".
The application and app has been recreated with the latest stable version of Django in October/2016

### CODE REVIEW

**Comment by andrewsmedina** [comment]
@jroqueweb why do you have closed this PR?

**Comment by jroquejr** [comment]
Because i didn't have understanding the real motive of mysql database as default in django example. My pull request has change from mysql to sqlite to turn django example app in tsuru more easy. But mysql remoto expands the concept from this example.

**Comment by andrewsmedina** [comment]
The real motive was a try to have an example that uses  `tsuru mysql service`. But I believe that it not worked well. 

To have an `Django` example that works is more important.

I'm +1 for you resend your PR :)

**Comment by andrewsmedina** [comment]
@jroqueweb thank you!

**Pull request merged**
